import { Dosis } from 'next/font/google'
import './globals.css'
import Navbar from './navbar'
import Footer from './footer'

const dosis = Dosis({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=' scrollbar-thumb-[#141935] scrollbar-[#03091A] scrollbar-thin select-none'>
      <body className={dosis.className}>
        <Navbar/>
        {children}
        <Footer date={"2023"}/>
        </body>
    </html>
  )
}
